./OPT.exe --inputList=data/inputs_for_displacedjet/list_of_list_MS-40_ctauS-100.txt --TF_Unc=0.3
./OPT.exe --inputList=data/inputs_for_displacedjet/list_of_list_MS-40_ctauS-100.txt --TF_Unc=0.4
./OPT.exe --inputList=data/inputs_for_displacedjet/list_of_list_MS-40_ctauS-100.txt --TF_Unc=0.5
./OPT.exe --inputList=data/inputs_for_displacedjet/list_of_list_MS-40_ctauS-100.txt --TF_Unc=0.6
./OPT.exe --inputList=data/inputs_for_displacedjet/list_of_list_MS-40_ctauS-100.txt --TF_Unc=0.7
./OPT.exe --inputList=data/inputs_for_displacedjet/list_of_list_MS-40_ctauS-100.txt --TF_Unc=0.8
./OPT.exe --inputList=data/inputs_for_displacedjet/list_of_list_MS-40_ctauS-100.txt --TF_Unc=0.9
./OPT.exe --inputList=data/inputs_for_displacedjet/list_of_list_MS-40_ctauS-100.txt --TF_Unc=1.0
./OPT.exe --inputList=data/inputs_for_displacedjet/list_of_list_MS-40_ctauS-100.txt --TF_Unc=1.5
./OPT.exe --inputList=data/inputs_for_displacedjet/list_of_list_MS-40_ctauS-100.txt --TF_Unc=-1
